# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ca31a0430cc358b70c30b264b89ceda36a219d44e1b6a587da99a13f5fb5a84bbb2f03a255a8c084824e60c70749ec32866e8e8753e72cdcb810351bcdc4490

test:
  secret_key_base: 53467c699efebe597e1544b489ae10c056d7e608edbd50079c831edd350a5c462cb07489f7694367191bb91820dac6b30aa6e3ddc65d9e2f11fffb4f6acb818d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
